FROM python:3.13.3-slim

WORKDIR /app

RUN apt-get update \
    && apt-get -y install libpq-dev gcc

COPY requirements.txt ./

RUN pip install -r requirements.txt

COPY . .

RUN python manage.py makemigrations
RUN python manage.py makemigrations lit3d

EXPOSE 8000

CMD ["sh", "-c", "entrypoint.sh"]