# Generated by Django 5.2 on 2025-04-28 07:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ProjectCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=255, verbose_name="Название раздела"),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Описание раздела"),
                ),
                ("slug", models.SlugField(unique=True)),
            ],
            options={
                "verbose_name": "Раздел проектов",
                "verbose_name_plural": "Разделы проектов",
            },
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=255, verbose_name="Название проекта"),
                ),
                ("slug", models.SlugField(unique=True)),
                ("date", models.DateField(verbose_name="Дата проекта")),
                (
                    "is_published",
                    models.BooleanField(default=True, verbose_name="Опубликовано?"),
                ),
                (
                    "preview_image",
                    models.ImageField(
                        upload_to="projects/previews/", verbose_name="Превью проекта"
                    ),
                ),
                (
                    "large_image",
                    models.ImageField(
                        upload_to="projects/large/",
                        verbose_name="Большая картинка проекта",
                    ),
                ),
                (
                    "video",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="projects/videos/",
                        verbose_name="Видео для проекта",
                    ),
                ),
                (
                    "short_description",
                    models.TextField(verbose_name="Краткое описание"),
                ),
                (
                    "full_description",
                    models.TextField(verbose_name="Подробное описание"),
                ),
                ("content", models.TextField(verbose_name="Контент (HTML)")),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="projects",
                        to="lit3d.projectcategory",
                        verbose_name="Раздел проектов",
                    ),
                ),
            ],
            options={
                "verbose_name": "Проект",
                "verbose_name_plural": "Проекты",
            },
        ),
    ]
