# Generated by Django 4.2.16 on 2025-04-09 08:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PortfolioPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название проекта')),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True, verbose_name='URL-адрес')),
                ('section', models.CharField(choices=[('russia', 'Выставка Россия'), ('rmi', 'Россия - моя история'), ('exhibition', 'Выставочные пространства'), ('PDA', 'PlayDigital Art'), ('concepts', 'Концепты')], default='exhibition', max_length=50, verbose_name='Раздел')),
                ('date', models.DateField(default=datetime.date(2023, 1, 1), verbose_name='Дата проекта')),
                ('description_short', models.TextField(blank=True, max_length=500, null=True, verbose_name='Краткое описание')),
                ('description_extended', models.TextField(blank=True, null=True, verbose_name='Подробное описание')),
                ('content', models.TextField(blank=True, null=True, verbose_name='Контент (HTML)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Опубликовано')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок сортировки')),
            ],
            options={
                'verbose_name': 'Страница проекта',
                'verbose_name_plural': 'Страницы проектов',
                'ordering': ['-date', 'order'],
            },
        ),
    ]
