# Generated by Django 5.2 on 2025-04-28 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lit3d", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContactInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("email", models.EmailField(blank=True, max_length=255, null=True)),
                (
                    "instagram_url",
                    models.URLField(blank=True, max_length=255, null=True),
                ),
                ("vk_url", models.URLField(blank=True, max_length=255, null=True)),
                (
                    "pinterest_url",
                    models.URLField(blank=True, max_length=255, null=True),
                ),
                ("behance_url", models.URLField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "photo",
                    models.ImageField(
                        blank=True, null=True, upload_to="employee_photos/"
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("position", models.CharField(max_length=255)),
                ("is_published", models.BooleanField(default=False)),
            ],
        ),
    ]
