# Generated by Django 5.2 on 2025-04-28 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lit3d", "0002_contactinfo_employee"),
    ]

    operations = [
        migrations.CreateModel(
            name="Slogans",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("main_heading", models.CharField(max_length=256)),
                ("main_subheading", models.CharField(max_length=256)),
                ("about_heading", models.CharField(max_length=256)),
                ("about_text", models.CharField(max_length=256)),
                ("slogan", models.CharField(max_length=256)),
                ("contact_heading", models.CharField(max_length=256)),
                ("contact_subheading", models.CharField(max_length=256)),
            ],
            options={
                "verbose_name": "Слоганы",
                "verbose_name_plural": "Слоганы",
            },
        ),
        migrations.AlterModelOptions(
            name="contactinfo",
            options={
                "verbose_name": "Контактные данные",
                "verbose_name_plural": "Контактные данные",
            },
        ),
        migrations.AlterModelOptions(
            name="employee",
            options={"verbose_name": "Сотрудник", "verbose_name_plural": "Сотрудники"},
        ),
    ]
