# Generated by Django 5.2 on 2025-04-28 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lit3d", "0003_slogans_alter_contactinfo_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="slogans",
            name="about_heading",
            field=models.CharField(max_length=512),
        ),
        migrations.AlterField(
            model_name="slogans",
            name="about_text",
            field=models.CharField(max_length=512),
        ),
        migrations.AlterField(
            model_name="slogans",
            name="contact_heading",
            field=models.CharField(max_length=512),
        ),
        migrations.AlterField(
            model_name="slogans",
            name="contact_subheading",
            field=models.CharField(max_length=512),
        ),
        migrations.AlterField(
            model_name="slogans",
            name="main_heading",
            field=models.CharField(max_length=512),
        ),
        migrations.AlterField(
            model_name="slogans",
            name="main_subheading",
            field=models.CharField(max_length=512),
        ),
        migrations.AlterField(
            model_name="slogans",
            name="slogan",
            field=models.CharField(max_length=512),
        ),
    ]
