# Generated by Django 5.2 on 2025-04-28 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lit3d", "0004_alter_slogans_about_heading_alter_slogans_about_text_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="slogans",
            name="about_heading",
            field=models.TextField(max_length=1024),
        ),
        migrations.AlterField(
            model_name="slogans",
            name="about_text",
            field=models.TextField(max_length=1024),
        ),
        migrations.AlterField(
            model_name="slogans",
            name="contact_heading",
            field=models.TextField(max_length=1024),
        ),
        migrations.AlterField(
            model_name="slogans",
            name="contact_subheading",
            field=models.TextField(max_length=1024),
        ),
        migrations.AlterField(
            model_name="slogans",
            name="main_heading",
            field=models.TextField(max_length=1024),
        ),
        migrations.AlterField(
            model_name="slogans",
            name="main_subheading",
            field=models.TextField(max_length=1024),
        ),
        migrations.AlterField(
            model_name="slogans",
            name="slogan",
            field=models.TextField(max_length=1024),
        ),
    ]
