# Generated by Django 5.2 on 2025-04-30 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lit3d", "0005_alter_slogans_about_heading_alter_slogans_about_text_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contactinfo",
            name="behance_url",
            field=models.URLField(
                blank=True, max_length=255, null=True, verbose_name="Behance URL"
            ),
        ),
        migrations.AlterField(
            model_name="contactinfo",
            name="email",
            field=models.EmailField(
                blank=True, max_length=255, null=True, verbose_name="email"
            ),
        ),
        migrations.AlterField(
            model_name="contactinfo",
            name="instagram_url",
            field=models.URLField(
                blank=True, max_length=255, null=True, verbose_name="Instagram URL"
            ),
        ),
        migrations.AlterField(
            model_name="contactinfo",
            name="phone_number",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="Номер телефона"
            ),
        ),
        migrations.AlterField(
            model_name="contactinfo",
            name="pinterest_url",
            field=models.URLField(
                blank=True, max_length=255, null=True, verbose_name="Pinterest URL"
            ),
        ),
        migrations.AlterField(
            model_name="contactinfo",
            name="vk_url",
            field=models.URLField(
                blank=True, max_length=255, null=True, verbose_name="VK URL"
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="is_published",
            field=models.BooleanField(default=False, verbose_name="Опубликовано?"),
        ),
        migrations.AlterField(
            model_name="employee",
            name="name",
            field=models.CharField(max_length=255, verbose_name="Имя"),
        ),
        migrations.AlterField(
            model_name="employee",
            name="photo",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="employee_photos/",
                verbose_name="Фото сотрдуника",
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="position",
            field=models.CharField(max_length=255, verbose_name="Позиция"),
        ),
        migrations.AlterField(
            model_name="project",
            name="content",
            field=models.TextField(
                blank=True, null=True, verbose_name="Контент (HTML)"
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="date",
            field=models.DateField(blank=True, null=True, verbose_name="Дата проекта"),
        ),
        migrations.AlterField(
            model_name="project",
            name="full_description",
            field=models.TextField(
                blank=True, null=True, verbose_name="Подробное описание"
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="large_image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="projects/large/",
                verbose_name="Большая картинка проекта",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="preview_image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="projects/previews/",
                verbose_name="Превью проекта",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="short_description",
            field=models.TextField(
                blank=True, null=True, verbose_name="Краткое описание"
            ),
        ),
    ]
