# Generated by Django 5.2 on 2025-05-12 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lit3d', '0006_alter_contactinfo_behance_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='order_number',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Порядковый номер'),
        ),
        migrations.AddField(
            model_name='project',
            name='order_number',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Порядковый номер'),
        ),
    ]
